name: Nix build

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  nix-build:
    name: Nix build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install nix action
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      # Set NIX_PATH to ensure nixpkgs and home-manager are available
      - name: Set NIX_PATH
        run: echo "NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/master.tar.gz:home-manager=https://github.com/nix-community/home-manager/archive/master.tar.gz" >> "$GITHUB_ENV"

      - name: Add nixpkgs and home-manager channels
        run: |
          nix-channel --add https://github.com/NixOS/nixpkgs/archive/master.tar.gz nixpkgs
          nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
          nix-channel --update

      - name: Run nix build
        run: nix build .#nixosConfigurations.desktop.config.system.build.toplevel

      - name: Run home-manager install
        run: nix-shell --experimental-features 'flakes' '<home-manager>' -A install

      - name: Build home-manager configuration
        run: home-manager build --flake .#desktop

      - name: Run nix flake check
        run: nix flake check
