---
name: Super-linter

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  super-linter:
    name: Super-linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run super-linter
        uses: github/super-linter@v7
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: ^/github/workspace/modules/home-manager/config/firefox/config/chrome/.*\.css$|^/github/workspace/modules/shell/python/github/
          IGNORE_GITIGNORED_FILES: true
          VALIDATE_SHELL_SHFMT: false
  nix-build:
    name: Nix build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix build
      - run: nix flake check
