---
name: Super-linter

on: push

permissions:
  contents: read

jobs:
  super-linter:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Run super-linter
        uses: github/super-linter@v7
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: ^modules/shell/python/github/
          IGNORE_GITIGNORED_FILES: true
